"""create audit_logs table

Revision ID: 742c0cb3f354
Revises: 
Create Date: 2026-08-26 14:51:07.030782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '742c0cb3f354'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS compliance")
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('sanitized_text', sa.Text(), nullable=False),
    sa.Column('pii_detection', sa.JSON(), nullable=False),
    sa.Column('processing_time', sa.Integer(), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='compliance'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP SCHEMA IF EXISTS compliance CASCADE")
    op.drop_table('audit_logs', schema='compliance')
    # ### end Alembic commands ###
